/**
 * @description       : this class contains the method which will send the document for the signing when initiated
 * @author            : Khuman Singh Bhadoriya
 * @last modified on  : 01-19-2024
 * @last modified by  : Khuman Singh Bhadoriya
**/
public class DocuSignStatusTriggerHandler{
    public static void handleOrderComplete(final Id contactId) {
        SendEnvelopeFromTriggerController.voidEnvelope(contactId);
        SendEnvelopeFromTriggerController.sendEnvelope(contactId);
    }
}